
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA DIVIDE ELSE EQUALS FLOAT FLOATN GE GT ID IF INT INTEGER LBRACES LE LPAREN LT MAIN MINUS NE PLUS POWER RBRACES RPAREN SEMI SEMICOLON STRING TIMESinicio : INT MAIN LPAREN RPAREN blocoprincipalblocoprincipal : LBRACES declaracoes RBRACES SEMICOLONdeclaracoes : tipo ID SEMICOLON\n                    | tipo ID SEMICOLON declaracoestipo : INT\n            | FLOAT '
    
_lr_action_items = {'INT':([0,7,15,],[2,10,10,]),'$end':([1,6,14,],[0,-1,-2,]),'MAIN':([2,],[3,]),'LPAREN':([3,],[4,]),'RPAREN':([4,],[5,]),'LBRACES':([5,],[7,]),'FLOAT':([7,15,],[11,11,]),'RBRACES':([8,15,16,],[12,-3,-4,]),'ID':([9,10,11,],[13,-5,-6,]),'SEMICOLON':([12,13,],[14,15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'inicio':([0,],[1,]),'blocoprincipal':([5,],[6,]),'declaracoes':([7,15,],[8,16,]),'tipo':([7,15,],[9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> inicio","S'",1,None,None,None),
  ('inicio -> INT MAIN LPAREN RPAREN blocoprincipal','inicio',5,'p_inicio','sint and sem meu.py',74),
  ('blocoprincipal -> LBRACES declaracoes RBRACES SEMICOLON','blocoprincipal',4,'p_blocoprincipal','sint and sem meu.py',79),
  ('declaracoes -> tipo ID SEMICOLON','declaracoes',3,'p_declaracoes','sint and sem meu.py',83),
  ('declaracoes -> tipo ID SEMICOLON declaracoes','declaracoes',4,'p_declaracoes','sint and sem meu.py',84),
  ('tipo -> INT','tipo',1,'p_tipo','sint and sem meu.py',98),
  ('tipo -> FLOAT','tipo',1,'p_tipo','sint and sem meu.py',99),
]
