# -*- coding: utf-8 -*-
"""T3 IA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCcWuiEK-4YyieOWyiMfxBxzfNaLnYAd

# Treinando agentes (Q-Learning e SARSA) no ambiente Taxi-v3 (Gymnasium)


Neste notebook treinaremos agentes usando **Q-Learning** e **SARSA** no ambiente **Taxi-v3** disponível na biblioteca `gymnasium`

## 📝 Detalhes do Ambiente: FrozenLake-v1 (Não Escorregadio)

Este experimento utilizou o ambiente **FrozenLake-v1** com o parâmetro `is_slippery=False`, tornando-o **determinístico** (a ação escolhida sempre resulta no movimento desejado).

---

### 🎯 Objetivo e Estrutura

| Detalhe | Descrição |
| :--- | :--- |
| **Objetivo** | O agente deve navegar do **Início (S)** até o **Objetivo (G)**, atravessando o lago congelado e **evitando cair nos Buracos (H)**. |
| **Grade** | O ambiente é uma grade de **$4 \times 4$**, totalizando 16 células/estados. |

| 0 (S) | 1 (F) | 2 (F) | 3 (F) |
| :--- | :--- | :--- | :--- |
| 4 (F) | 5 (H) | 6 (F) | 7 (H) |
| 8 (F) | 9 (F) | 10 (F)| 11 (H)|
| 12 (H)| 13 (F)| 14 (F)| 15 (G)|

| S = Start | F = Frozen (Seguro) | H = Hole (Buraco/Falha) | G = Goal (Objetivo/Sucesso) |

---

### 🗺️ Espaço de Ações e Observações

| Espaço | Detalhe | Tipo | Valores |
| :--- | :--- | :--- | :--- |
| **Ações** | Movimentos que o agente pode executar. | Discreto (4) | **0: Esquerda** ($\leftarrow$), **1: Baixo** ($\downarrow$), **2: Direita** ($\rightarrow$), **3: Cima** ($\uparrow$). |
| **Observações** | O estado atual do agente (célula da grade). | Discreto (16) | Estados de **0 a 15**. |

---

### 💰 Recompensas

A recompensa é esparsa (maioria dos passos retorna 0.0):

| Evento | Recompensa (`r`) | Resultado |
| :--- | :--- | :--- |
| Chegar ao **Objetivo (G)** | **$+1.0$** | Episódio termina (Sucesso) |
| Cair em um **Buraco (H)** | **$0.0$** | Episódio termina (Falha) |
| Qualquer outro passo (F) | **$0.0$** | Continua o episódio |

---

### 📈 Formação da Tabela Q (Q-Learning / SARSA)

A **Tabela Q** é uma matriz $16 \times 4$ que armazena o **valor esperado** de se tomar cada ação ($a$) em cada estado ($s$).

1.  **Inicialização:** $Q(s, a)$ é inicializada com **zeros**.
2.  **Ação:** O agente usa a estratégia **$\epsilon$-greedy**, equilibrando a **Exploração** ($\epsilon$) com a **Explotação** ($1 - \epsilon$).
3.  **Atualização:** A Tabela Q é ajustada a cada passo com a **Equação de Bellman** (a diferença está no termo futuro):

| Algoritmo | Termo Futuro | Tipo de Política |
| :--- | :--- | :--- |
| **Q-Learning** | $\gamma \mathbf{\max_{a'} Q(s', a')}$ | **Off-policy** (Estimativa da melhor ação futura, ignorando a política usada para mover). |
| **SARSA** | $\gamma \mathbf{Q(s', a')}$ | **On-policy** (Estimativa baseada na próxima ação $a'$ que *será tomada* pelo agente, seguindo a política $\epsilon$-greedy). |
4.  **Convergência:** O valor de $\epsilon$ **decaía exponencialmente** de $1.0$ para $0.05$ ao longo dos episódios, garantindo que o agente transitasse de um comportamento puramente aleatório para um comportamento otimizado, explorando o conhecimento armazenado na Tabela Q.

Setup (instalar as dependências e importar libs)
"""

!pip install -q gymnasium==0.28.1
!pip install -q gymnasium[toy_text]
!pip install -q pandas numpy matplotlib seaborn

import gymnasium as gym
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
from IPython.display import clear_output

"""Funções utilitárias"""

def make_env():
    # FrozenLake: 4x4, 16 estados, 4 ações (N, S, L, O)
    # is_slippery=False: Ações são determinísticas (sem chance de escorregar)
    return gym.make('FrozenLake-v1', is_slippery=False)


def epsilon_by_episode(initial_epsilon, min_epsilon, decay_rate, episode):
    # Decaimento exponencial de epsilon
    return max(min_epsilon, initial_epsilon * (decay_rate ** episode))

"""Implementação: Q-Learning (tabular)"""

def train_q_learning(env,
                     num_episodes=5000,
                     max_steps=100,
                     alpha=0.1,
                     gamma=0.99,
                     initial_epsilon=1.0,
                     min_epsilon=0.01,
                     decay_rate=0.999):

    n_states = env.observation_space.n
    n_actions = env.action_space.n

    q_table = np.zeros((n_states, n_actions))
    rewards_all_episodes = []
    epsilons = []

    for episode in range(num_episodes):
        state, _ = env.reset()
        total_reward = 0
        epsilon = epsilon_by_episode(initial_epsilon, min_epsilon, decay_rate, episode)
        epsilons.append(epsilon)

        for step in range(max_steps):
            # Escolha de ação (epsilon-greedy)
            if random.random() < epsilon:
                action = random.randrange(n_actions)
            else:
                action = int(np.argmax(q_table[state]))

            # Executar ação
            next_state, reward, terminated, truncated, _ = env.step(action)
            done = terminated or truncated

            # Atualização Q-Learning (Off-policy: usa max(Q) do próximo estado)
            best_next = np.max(q_table[next_state])
            td_target = reward + gamma * best_next
            td_error = td_target - q_table[state, action]
            q_table[state, action] += alpha * td_error

            state = next_state
            total_reward += reward

            if done:
                break

        rewards_all_episodes.append(total_reward)

    return q_table, rewards_all_episodes, epsilons

"""## 5) Implementação SARSA (policy)"""

def train_sarsa(env,
                num_episodes=5000,
                max_steps=100,
                alpha=0.1,
                gamma=0.99,
                initial_epsilon=1.0,
                min_epsilon=0.01,
                decay_rate=0.999):

    n_states = env.observation_space.n
    n_actions = env.action_space.n

    q_table = np.zeros((n_states, n_actions))
    rewards_all_episodes = []
    epsilons = []

    for episode in range(num_episodes):
        state, _ = env.reset()

        epsilon = epsilon_by_episode(initial_epsilon, min_epsilon, decay_rate, episode)
        epsilons.append(epsilon)

        # Escolher ação inicial via epsilon-greedy
        if random.random() < epsilon:
            action = random.randrange(n_actions)
        else:
            action = int(np.argmax(q_table[state]))

        total_reward = 0

        for step in range(max_steps):
            next_state, reward, terminated, truncated, _ = env.step(action)
            done = terminated or truncated

            # Próxima ação (on-policy) via epsilon-greedy
            if random.random() < epsilon:
                next_action = random.randrange(n_actions)
            else:
                next_action = int(np.argmax(q_table[next_state]))

            # Atualização SARSA (On-policy: usa Q(s', a') da próxima ação *escolhida*)
            td_target = reward + gamma * q_table[next_state, next_action]
            td_error = td_target - q_table[state, action]
            q_table[state, action] += alpha * td_error

            state = next_state
            action = next_action
            total_reward += reward

            if done:
                break

        rewards_all_episodes.append(total_reward)

    return q_table, rewards_all_episodes, epsilons

"""# 6) Treinamento com variação de hiperparâmetros e registro de resultados"""

env = make_env()

algorithms = {
    'Q-Learning': train_q_learning,
    'SARSA': train_sarsa
}

alphas = [0.1, 0.5]
gammas = [0.9, 0.99]

results = []

num_episodes = 5000
max_steps = 100
initial_epsilon = 1.0
min_epsilon = 0.05
decay_rate = 0.999

for alg_name, alg_func in algorithms.items():
    for alpha in alphas:
        for gamma in gammas:

            q_table, rewards, eps_history = alg_func(
                env,
                num_episodes=num_episodes,
                max_steps=max_steps,
                alpha=alpha,
                gamma=gamma,
                initial_epsilon=initial_epsilon,
                min_epsilon=min_epsilon,
                decay_rate=decay_rate
            )

            rewards = np.array(rewards)
            mean_last_100 = rewards[-100:].mean()
            success_rate = np.mean(rewards)
            final_epsilon = eps_history[-1]

            results.append({
                'algorithm': alg_name,
                'alpha': alpha,
                'gamma': gamma,
                'mean_reward_last_100': mean_last_100,
                'success_rate': success_rate,
                'final_epsilon': final_epsilon,
                'rewards_series': rewards
            })

summary_df = pd.DataFrame([
    {k: v for k, v in r.items() if k != 'rewards_series'}
    for r in results
])

print("\n--- Resumo dos Resultados ---")
print(summary_df)

for alg_name in algorithms.keys():
    subset = summary_df[summary_df['algorithm'] == alg_name]
    pivot = subset.pivot(index='alpha', columns='gamma', values='mean_reward_last_100')
    plt.figure(figsize=(6, 4))
    sns.heatmap(pivot, annot=True, fmt='.3f', cmap='viridis', cbar_kws={'label': 'Média de Recompensa (Últimos 100)'})
    plt.title(f'Média de Recompensa (alg={alg_name})')
    plt.show()

"""# Salvar resumo em CSV"""

summary_df.to_csv('rl_summary_frozenlake.csv', index=False)
print('\nResumo salvo em rl_summary_frozenlake.csv')